### ISSUE TITLE
Support "modulepreload"

### ISSUE THREAD

**Issue by nathanchicken** [N0ps32/http-2-server-push-twig#1]
Hi,

Have just tried this out and it's a great convenience, thanks for the plugin. It's working great for styles.

We're using a bit of a complicated set up for our JavaScript though -we're compiling a modern and legacy build using the module approach, as described in this article:

https://philipwalton.com/articles/deploying-es2015-code-in-production-today/

Eg:
```
<script async type="module" src="{{ '/assets/production/app.js' | h2push( 'modulepreload' ) }}"></script>
<script nomodule src="/assets/legacy/legacy-app.js"></script>
```

Because our production bundle is a 'module' rather than a script, the preload is a bit different, I'm taking my cues from here and need to use `modulepreload`:
https://developers.google.com/web/updates/2017/12/modulepreload

When I do this in the HTML:
`<link rel="modulepreload" href="/assets/production/app.js">`

Chrome doesn't complain at the lack of "as" there like it might with other scripts and it all seems to work fine.  But when I use the above code ( `ht2push('modulepreload')` ) it obviously doesn't work because `as=modulepreload` isnt' the right header.

I think it needs to be like this:

`</assets/production/app.js>; rel=modulepreload;`

But without modifying the plugin's code I can't make that header happen. Would be great if this was supported! Perhaps just specifying "as" to be optionally omitted?

**Comment by RaederDev** [comment]
Hi!

This is now supported using the h2module filter:
https://github.com/N0ps32/http-2-server-push-twig#using-http2-server-push-twig-modulepreload

Let me know if you run into any issues (tho I did test it successfully locally).
